server:
  port: 8080

spring:
  datasource:
    username: root
    password: 2546
    url: jdbc:mysql://localhost:3306/search_engine_test?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: never

indexing-settings:
  sites:
    - url: https://lenta.ru
      name: Лента.ру
#    - url: https://www.skillbox.ru
#      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru

jwt:
  secret:
    key:
      access:
        value: +XcBbJEjbqbx9aZ+WKItBAhfq6yszfdZ7WDjaH/ukFg=
        max-age: 300
      refresh:
        value: yynwwLF6Fgs9Sz4Jiq2nnzlHsv/C7wCY4GB8+pW97D8=
        max-age: 3600