openapi: 3.0.1
info:
  title: News KMD
  description: Поисковый движок по новостным сайтам
  contact:
    name: Мельчаков Дмитрий
    email: melchakov.d@mail.ru
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /user/api/indexPage:
    post:
      tags:
        - API
      summary: Запуск индексации отдельной страницы
      operationId: indexPage
      parameters:
        - name: url
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/IndexingResponse'
      security:
        - JWT: []
  /auth/sign-up:
    post:
      tags:
        - Аутентификация
      summary: Регистрация пользователя
      operationId: signUp
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/JwtAuthenticationResponse'
  /auth/sign-in:
    post:
      tags:
        - Аутентификация
      summary: Авторизация пользователя
      operationId: signIn
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/JwtAuthenticationResponse'
  /auth/refresh:
    get:
      tags:
        - Аутентификация
      summary: Получить новый refresh токен из куки
      operationId: refresh_1
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/JwtAuthenticationResponse'
      security:
        - JWT: []
    post:
      tags:
        - Аутентификация
      summary: Получить новый refresh токен из запроса
      operationId: refresh
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshJwtRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/JwtAuthenticationResponse'
      security:
        - JWT: []
  /user/api/stopIndexing:
    get:
      tags:
        - API
      summary: Остановка текущей индексации
      operationId: stopIndexing
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/IndexingResponse'
      security:
        - JWT: []
  /user/api/statistics:
    get:
      tags:
        - API
      summary: Запрос статистики
      operationId: statistics
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/StatisticsResponse'
      security:
        - JWT: []
  /user/api/startIndexing:
    get:
      tags:
        - API
      summary: Запуск полной индексации
      operationId: startIndexing
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/IndexingResponse'
      security:
        - JWT: []
  /user/api/search:
    get:
      tags:
        - API
      summary: Поиск
      operationId: search
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
        - name: site
          in: query
          required: false
          schema:
            type: string
            default: ''
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 0
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 20
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SearchResponse'
      security:
        - JWT: []
  /auth/logout:
    get:
      tags:
        - Аутентификация
      summary: Выход из системы
      operationId: logout
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/LogoutJwtResponse'
      security:
        - JWT: []
components:
  schemas:
    IndexingResponse:
      type: object
      properties:
        result:
          type: boolean
          description: Результат запуска/остановки индексации
        error:
          type: string
          description: Текст ошибки
      description: Ответ при запуске/остановке индексации
    SignUpRequest:
      required:
        - email
        - username
      type: object
      properties:
        username:
          maxLength: 50
          minLength: 5
          type: string
          description: Имя пользователя
          example: Ocolus
        password:
          maxLength: 255
          minLength: 5
          type: string
          description: Пароль
          example: Aa12345
        email:
          maxLength: 50
          minLength: 5
          type: string
          description: Адрес электронной почты
          example: ocolus@gmail.com
      description: Запрос на регистрацию
    JwtAuthenticationResponse:
      type: object
      properties:
        accessToken:
          type: string
          description: Access токен
        refreshToken:
          type: string
          description: Refresh токен
      description: Ответ с токенами при аутентификации
    SignInRequest:
      type: object
      properties:
        username:
          maxLength: 50
          minLength: 5
          type: string
          description: Имя пользователя
          example: Ocolus
        password:
          maxLength: 255
          minLength: 5
          type: string
          description: Пароль
          example: Aa12345
      description: Запрос на аутентификацию
    RefreshJwtRequest:
      type: object
      properties:
        refreshToken:
          type: string
          description: Refresh токен
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ...
      description: Зпрос на обновление токенов
    DetailedStatisticsItem:
      type: object
      properties:
        url:
          type: string
          description: URL сайта
        name:
          type: string
          description: Название сайта
        status:
          type: string
          description: Статус индексации
        statusTime:
          type: integer
          description: Время установления статуса индексации
          format: int64
        error:
          type: string
          description: Текст ошибки
        pages:
          type: integer
          description: Кол-во проиндексированных страниц
          format: int32
        lemmas:
          type: integer
          description: Кол-во найденных лемм
          format: int32
      description: Подробная статистика сайта
    StatisticsData:
      type: object
      properties:
        total:
          $ref: '#/components/schemas/TotalStatistics'
        detailed:
          type: array
          description: Подробная статистика по каждому сайту
          items:
            $ref: '#/components/schemas/DetailedStatisticsItem'
      description: Статистика
    StatisticsResponse:
      type: object
      properties:
        result:
          type: boolean
          description: Результат запроса статистики
        statistics:
          $ref: '#/components/schemas/StatisticsData'
      description: Статистика содержащихся страниц
    TotalStatistics:
      type: object
      properties:
        sites:
          type: integer
          description: Кол-во сайтов
          format: int32
        pages:
          type: integer
          description: Кол-во страниц
          format: int32
        lemmas:
          type: integer
          description: Кол-во лемм
          format: int32
        indexing:
          type: boolean
          description: Индексация запущена/не запущена
      description: Глобальная статистика
    SearchResponse:
      type: object
      properties:
        result:
          type: boolean
          description: Результат поиска
        count:
          type: integer
          description: Кол-во найденных страниц
          format: int32
        data:
          type: array
          description: Список найденных страниц
          items:
            $ref: '#/components/schemas/SearchResult'
        error:
          type: string
          description: Текст ошибка
      description: Результат поискового запроса
    SearchResult:
      type: object
      properties:
        site:
          type: string
          description: URL сайта
        siteName:
          type: string
          description: Имя сайта
        uri:
          type: string
          description: Путь страницы
        title:
          type: string
          description: Заголовок страницы
        snippet:
          type: string
          description: Фрагмент текста, в котором найдены совпадения в формате HTML
        relevance:
          type: number
          description: Релевантность страницы
          format: float
      description: Найденная страница
    LogoutJwtResponse:
      type: object
      properties:
        statusCode:
          type: string
          description: Код ответа
          enum:
            - 100 CONTINUE
            - 101 SWITCHING_PROTOCOLS
            - 102 PROCESSING
            - 103 EARLY_HINTS
            - 103 CHECKPOINT
            - 200 OK
            - 201 CREATED
            - 202 ACCEPTED
            - 203 NON_AUTHORITATIVE_INFORMATION
            - 204 NO_CONTENT
            - 205 RESET_CONTENT
            - 206 PARTIAL_CONTENT
            - 207 MULTI_STATUS
            - 208 ALREADY_REPORTED
            - 226 IM_USED
            - 300 MULTIPLE_CHOICES
            - 301 MOVED_PERMANENTLY
            - 302 FOUND
            - 302 MOVED_TEMPORARILY
            - 303 SEE_OTHER
            - 304 NOT_MODIFIED
            - 305 USE_PROXY
            - 307 TEMPORARY_REDIRECT
            - 308 PERMANENT_REDIRECT
            - 400 BAD_REQUEST
            - 401 UNAUTHORIZED
            - 402 PAYMENT_REQUIRED
            - 403 FORBIDDEN
            - 404 NOT_FOUND
            - 405 METHOD_NOT_ALLOWED
            - 406 NOT_ACCEPTABLE
            - 407 PROXY_AUTHENTICATION_REQUIRED
            - 408 REQUEST_TIMEOUT
            - 409 CONFLICT
            - 410 GONE
            - 411 LENGTH_REQUIRED
            - 412 PRECONDITION_FAILED
            - 413 PAYLOAD_TOO_LARGE
            - 413 REQUEST_ENTITY_TOO_LARGE
            - 414 URI_TOO_LONG
            - 414 REQUEST_URI_TOO_LONG
            - 415 UNSUPPORTED_MEDIA_TYPE
            - 416 REQUESTED_RANGE_NOT_SATISFIABLE
            - 417 EXPECTATION_FAILED
            - 418 I_AM_A_TEAPOT
            - 419 INSUFFICIENT_SPACE_ON_RESOURCE
            - 420 METHOD_FAILURE
            - 421 DESTINATION_LOCKED
            - 422 UNPROCESSABLE_ENTITY
            - 423 LOCKED
            - 424 FAILED_DEPENDENCY
            - 425 TOO_EARLY
            - 426 UPGRADE_REQUIRED
            - 428 PRECONDITION_REQUIRED
            - 429 TOO_MANY_REQUESTS
            - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
            - 451 UNAVAILABLE_FOR_LEGAL_REASONS
            - 500 INTERNAL_SERVER_ERROR
            - 501 NOT_IMPLEMENTED
            - 502 BAD_GATEWAY
            - 503 SERVICE_UNAVAILABLE
            - 504 GATEWAY_TIMEOUT
            - 505 HTTP_VERSION_NOT_SUPPORTED
            - 506 VARIANT_ALSO_NEGOTIATES
            - 507 INSUFFICIENT_STORAGE
            - 508 LOOP_DETECTED
            - 509 BANDWIDTH_LIMIT_EXCEEDED
            - 510 NOT_EXTENDED
            - 511 NETWORK_AUTHENTICATION_REQUIRED
        message:
          type: string
          description: Сообщение
      description: Результат выхода из системы
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
